apiVersion: v1
kind: Service
metadata:
  name: basic-healthcare-service
  labels:
    app: basic-healthcare-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: basic-healthcare-app
